### ISSUE TITLE
feat: add dialogs

### ISSUE THREAD

**Issue by techmaved** [2223-Project-1/OmegaPass#52]
**Describe the solution you'd like**
- Dialog for adding a password
- Dialog for account settings
- Rewrite dialog for edit password

**Comment by lvlcn-t** [comment]
## Changes so far

- [feat: add dialogs and js function snippets](https://github.com/2223-Project-1/OmegaPass/commit/5c453c094c536c40cb075005b39b7d13ad5a1aad)
- [Merge branch 'main' into feat/dialogs](https://github.com/2223-Project-1/OmegaPass/commit/62096f3f83f78efb246bb75eb2b96c49683c24a6)
- [style: correct misspelling](https://github.com/2223-Project-1/OmegaPass/commit/e45c58f9b1e6c67bf6ecf7019d993770f2ab62d1)
- [feat: add edit password dialog logic](https://github.com/2223-Project-1/OmegaPass/commit/332dcb664dec0d4bf8e9d5ab43fda23ec13915f8)
- [feat: add account settings dialog logic](https://github.com/2223-Project-1/OmegaPass/commit/f5e95a4f668a3bb28e7a7260da86f5fcace03537)
- [feat: add add password dialog logic](https://github.com/2223-Project-1/OmegaPass/commit/eccfca75bc8e9f3f137b5c99ce101aa9d74110e7)
- [chore: merge 'feat/styles' into 'feat/dialogs'](https://github.com/2223-Project-1/OmegaPass/commit/b8d07ec5922434204e0f646e963b6f41b4b804ba)
- [chore: rm merge issues](https://github.com/2223-Project-1/OmegaPass/commit/dbfdf3e1004ca8b35a617bf6161a62fc7b940fc4)
- [fix: add custom dialogs and rm jquery ui dialogs](https://github.com/2223-Project-1/OmegaPass/commit/9299a34182d1d9957f9ff962cf9944d9f2e94976)
- [chore: add footer styles to scss](https://github.com/2223-Project-1/OmegaPass/commit/e58c243461fb468f22090588e728682a86bd6ced)
- [docs: comment open TODOs and bugs](https://github.com/2223-Project-1/OmegaPass/commit/45b1b4fe906ccb9224685148c510ec6207d46f73)

## TODO

### Edit entry modal
  - [ ] display the website field (label + input) to inline over the complete dialog content width
  - [ ] display the username/password label + input to below each other. Each over 1/2 the width of the dialog content
  - [ ] display the buttons 1/2 the width of the dialog content below the inputs
  - [ ] **BUG**: The ajax json response for redirect is not working. Response so far:
  ```['success' => {{BOOLEAN}}, 'redirect' => {{PATH}}]```
  - [ ] **BUG**: The errormsg is not displayed

### Account settings modal
  - [ ] add panels to the modal where the user can switch between the two settings modes
  - [ ] Panel 1: change account username ; Panel 2: change account password
  - [ ] **BUG**: The ajax json response for redirect is not working. Response so far:
  ```['success' => {{BOOLEAN}}, 'redirect' => {{PATH}}]```
  - [ ] **BUG**: The errormsg is not displayed

### Add entry modal
  - [ ] display the website field (label + input) to inline over the complete dialog content width
  - [ ] display the username/password label + input to below each other. Each over 1/2 the width of the dialog content
  - [ ] add generate password frontend function
    - [ ] after the generate password button is clicked another menu opens for the settings of the generation
    - [ ] after the fill button is pressed the additional menu closes and the password is automatically pasted in the password field
  - [ ] add logic to the show password button
  - [ ] display the buttons 1/2 the width of the dialog content below the inputs
  - [ ] **BUG**: The ajax json response for redirect is not working. Response so far:
  ```['success' => {{BOOLEAN}}, 'redirect' => {{PATH}}]```
  - [ ] **BUG**: The errormsg is not displayed

**Comment by lvlcn-t** [comment]
## TODO
#41 added these features to this issue
- [ ] Copy to clipboard feature for username / password
- [ ] Open website in new tab
- [ ] OPTIONAL: Edit tab with prefilled data, so you don't have to retype e.g. the whole website URL for a one letter change

**Comment by lvlcn-t** [comment]
@techmaved If you could help me with these ToDo's I'd be very grateful.

### All dialogs
- [ ] display the dialog correctly in the center
- [ ] display background behind dialogs with background-color: rgba(0,0,0,0.4);
- [ ] let the modals be faded in

### Edit entry modal
- [ ] display the website field (label + input) to inline over the complete dialog content width
- [ ] display the username/password label + input to below each other. Each over 1/2 the width of the dialog content
- [ ] display the buttons 1/2 the width of the dialog content below the inputs

### Account settings modal
- [ ] add [tabs](https://www.w3schools.com/w3css/w3css_tabulators.asp) to the modal where the user can switch between the two settings modes
- [ ] tab 1: change account username ; tab 2: change account password
- [ ] fix: add change button for change username

### Add entry modal
- [ ] display the website field (label + input) to inline over the complete dialog content width
- [ ] display the username/password label + input to below each other. Each over 1/2 the width of the dialog content
	- [ ] after the generate password button is clicked another menu opens for the settings of the generation
- [ ] display the buttons 1/2 the width of the dialog content below the inputs

**Comment by techmaved** [comment]
@lvlcn-t Didn't saw this in the TODOs, but I think this is a useful feature: 2b0cd620fe70752a13889215952cbeb6259cf9c9

**Comment by lvlcn-t** [comment]
Encountered bug: If you want to reload the overview page this alert comes. This should not be the case.
![image](https://github.com/2223-Project-1/OmegaPass/assets/75443136/14bc018c-94a1-4ecf-9094-761b3bd95c88)

**Comment by lvlcn-t** [comment]
## TODO
- [ ] add toggle show password in edit modal

**Comment by lvlcn-t** [comment]
@techmaved could you adjust the password style here?
![image](https://github.com/2223-Project-1/OmegaPass/assets/75443136/3c0e8721-4522-4d80-add2-6940514704b9)

**Comment by lvlcn-t** [comment]
> > Encountered bug: If you want to reload the overview page this alert comes. This should not be the case. ![image](https://user-images.githubusercontent.com/75443136/238465954-14bc018c-94a1-4ecf-9094-761b3bd95c88.png)
> 
> What did do before?

I cannot remember what I've done and cannot rebuild the scenario.
Let's just keep it in mind for later if someone opens an issue.

**Comment by techmaved** [comment]
> > > Encountered bug: If you want to reload the overview page this alert comes. This should not be the case. ![image](https://user-images.githubusercontent.com/75443136/238465954-14bc018c-94a1-4ecf-9094-761b3bd95c88.png)
> > 
> > 
> > What did do before?
> 
> I cannot remember what I've done and cannot rebuild the scenario. Let's just keep it in mind for later if someone opens an issue.

It happens when you e. g. move a password out the trash and click back in the browser
